<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
	<RuntimeIdentifier>win-x64</RuntimeIdentifier>
	  <PlatformTarger>x64</PlatformTarger>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Features\InfiniteCanvas\" />
    <Folder Include="Features\ProjectSelector\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="TreeSitterLanguagePack" Version="1.10.9" />
  </ItemGroup>

</Project>
